### ISSUE TITLE
Bug in asm example code

### ISSUE THREAD

**Issue by ChillyWillyGuru** [b1tsh1ft3r/retro.link#1]
There is a bug in the example assembly code. In the initialization, when the cart is present, it falls into the code for when the cart is not present, and so the cart is never signaled as present.

```
    move.b  #$07, UART_FCR   ;  flush send/receive fifos
    move.b  #$00, UART_IER
    move.b  #1,cart_present
@Not_Found:
    clr.b   cart_present
    rts
```

There needs to be a rts after setting cart_present to 1.

**Comment by b1tsh1ft3r** [comment]
Thanks for the catch. I was moving a bit fast putting this example together and clearly forgot! Fixed.
